#!/bin/sh

# Copyright (C) 2012, Aravinda VK <mail@aravindavk.in>
#                          http://aravindavk.in

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

if [ $# -ne 1 ]
then
  echo "Usage: $0 <version>"
  exit $E_BADARGS
fi

rm -rf /tmp/gubbi-kannada-ttf-$1
mkdir /tmp/gubbi-kannada-ttf-$1
cp ../ChangeLog ../COPYING ../Gubbi.ttf ../README /tmp/gubbi-kannada-ttf-$1/

rm -rf /tmp/gubbi-kannada-$1
mkdir /tmp/gubbi-kannada-$1
cp ../ChangeLog ../COPYING ../Gubbi.sfd ../generate.pe ../Makefile ../README /tmp/gubbi-kannada-$1/

cd /tmp/
tar -cvzf gubbi-kannada-ttf-$1.tar.gz gubbi-kannada-ttf-$1/
tar -cvzf gubbi-kannada-$1.tar.gz gubbi-kannada-$1/
rm -rf gubbi-kannada-ttf-$1
rm -rf gubbi-kannada-$1
